package modelo.entidad;
// Generated 10-17-2021 04:09:49 PM by Hibernate Tools 4.3.1



/**
 * Clinica generated by hbm2java
 */
public class Clinica  implements java.io.Serializable {


     private Integer id;
     private String doctores;
     private String pacientes;
     private String medicamento;
     private String sucursales;
     private String proveedores;
     private String instrumentos;

    public Clinica() {
    }

    public Clinica(String doctores, String pacientes, String medicamento, String sucursales, String proveedores, String instrumentos) {
       this.doctores = doctores;
       this.pacientes = pacientes;
       this.medicamento = medicamento;
       this.sucursales = sucursales;
       this.proveedores = proveedores;
       this.instrumentos = instrumentos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDoctores() {
        return this.doctores;
    }
    
    public void setDoctores(String doctores) {
        this.doctores = doctores;
    }
    public String getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(String pacientes) {
        this.pacientes = pacientes;
    }
    public String getMedicamento() {
        return this.medicamento;
    }
    
    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }
    public String getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(String sucursales) {
        this.sucursales = sucursales;
    }
    public String getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(String proveedores) {
        this.proveedores = proveedores;
    }
    public String getInstrumentos() {
        return this.instrumentos;
    }
    
    public void setInstrumentos(String instrumentos) {
        this.instrumentos = instrumentos;
    }




}


